/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neevtech.callguard.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author ashish
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(com.neevtech.callguard.services.CallReportsFacadeREST.class);
        resources.add(com.neevtech.callguard.services.NumbersFacadeREST.class);
        resources.add(com.neevtech.callguard.services.GroupsFacadeREST.class);
        resources.add(com.neevtech.callguard.services.ReportedNumbersFacadeREST.class);
        resources.add(com.neevtech.callguard.services.UsersFacadeREST.class);
        resources.add(com.neevtech.callguard.services.CategoriesFacadeREST.class);
        try {
            Class<?> jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return resources;
    }
    
}
